Airbnb Listings

Task: Load the dataset, filter listings based on location and price, and sort by number of reviews.

In [1]:
import pandas as pd
import seaborn as sns
airbnb_listings_df = pd.read_csv('C:\\Users\\HP\\Documents\\listings_austin.csv')
airbnb_listings_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2265,Zen-East in the Heart of Austin (monthly rental),2466,Paddy,NaN,78702,30.277520,-97.713770,Entire home/apt,179,7,26,2021-07-02,0.36,3,35,2,NaN
1,5245,"Eco friendly, Colorful, Clean, Cozy monthly share",2466,Paddy,NaN,78702,30.276140,-97.713200,Private room,114,30,9,2017-02-24,0.21,3,0,0,NaN
2,5456,"Walk to 6th, Rainey St and Convention Ctr",8028,Sylvia,NaN,78702,30.260570,-97.734410,Entire home/apt,108,2,575,2021-09-25,24.16,1,324,39,NaN
3,5769,NW Austin Room,8186,Elizabeth,NaN,78729,30.456970,-97.784220,Private room,39,1,264,2021-07-03,5.95,1,0,7,NaN
4,6413,Gem of a Studio near Downtown,13879,Todd,NaN,78704,30.248850,-97.735870,Entire home/apt,109,3,117,2021-04-02,1.27,1,0,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11264,52772517,"Perfect for F1 | Modern, Cozy 1B Gem near Down...",243684594,Shirley,NaN,78756,30.319251,-97.732620,Entire home/apt,128,1,0,NaN,NaN,39,357,0,NaN
11265,52772519,"Perfect for F1 | Modern, Cozy 1B Gem near Down...",243684594,Shirley,NaN,78756,30.319457,-97.730823,Entire home/apt,120,1,0,NaN,NaN,39,364,0,NaN
11266,52773211,South Austin Duplex,29154315,David,NaN,78747,30.154323,-97.758275,Entire home/apt,257,2,0,NaN,NaN,2,80,0,NaN
11267,52775433,Upscale apartment home | 1 BR in Austin,359036978,Casey,NaN,78758,30.399703,-97.708126,Entire home/apt,157,90,0,NaN,NaN,293,365,0,NaN
11268,52777085,A home you will love | 1 BR in Austin,359036978,Casey,NaN,78702,30.280324,-97.710865,Entire home/apt,159,30,0,NaN,NaN,293,358,0,NaN

In [2]:
filtered3_df = airbnb_listings_df[(airbnb_listings_df['host_name']== 'Paddy') &
                                  (airbnb_listings_df['room_type']== 'Private room')]
filtered3_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
1,5245,"Eco friendly, Colorful, Clean, Cozy monthly share",2466,Paddy,NaN,78702,30.27614,-97.7132,Private room,114,30,9,2017-02-24,0.21,3,0,0,NaN

In [3]:
sorted_df = airbnb_listings_df.sort_values(by = 'number_of_reviews', ascending= False)
sorted_df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
319,949922,"Vintage Airstream in East Austin, Texas",5152543,Marcella,NaN,78723,30.297920,-97.679190,Entire home/apt,79,1,953,2021-09-28,12.68,2,316,127,NaN
395,1462311,Stay and Enjoy The Austin Texas House South Co...,740347,Chris,NaN,78704,30.246680,-97.756180,Entire home/apt,153,1,929,2021-10-05,13.68,1,289,95,NaN
320,951272,Downtown Austin Texas Condo,1648173,Kristen,NaN,78701,30.279860,-97.745360,Entire home/apt,106,1,849,2021-09-29,17.82,1,315,105,NaN
669,2528473,Garden Cottage in East Austin,5152543,Marcella,NaN,78723,30.297390,-97.682190,Entire home/apt,81,1,830,2021-09-29,9.11,2,316,109,NaN
62,202187,South Congress Studio Apartment,989596,John,NaN,78704,30.248670,-97.746780,Entire home/apt,87,1,817,2021-09-27,14.98,2,281,70,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
817,4078567,4 Bed Walking Distance to ACL,21155894,Kristofer,NaN,78704,30.255870,-97.751510,Entire home/apt,2100,3,0,NaN,NaN,1,0,0,NaN
7276,42327347,Lux east Austin apartment,336543891,Inga,NaN,78702,30.260750,-97.726500,Entire home/apt,290,2,0,NaN,NaN,1,0,0,NaN
7277,42333359,"Brand New, Quiet and Clean Bedroom / Bath",336618445,Lena,NaN,78723,30.296980,-97.699640,Private room,150,3,0,NaN,NaN,1,175,0,NaN
7279,42335050,"Kids, Friends, & Pets Oh My! Huge House Big B...",202289793,Navid,NaN,78753,30.394350,-97.658350,Entire home/apt,529,1,0,NaN,NaN,2,11,0,NaN
11268,52777085,A home you will love | 1 BR in Austin,359036978,Casey,NaN,78702,30.280324,-97.710865,Entire home/apt,159,30,0,NaN,NaN,293,358,0,NaN